services:
  service_syft:
    build: .
    container_name: service_syft
    ports:
      - "8003:8003"
    volumes:
      - apk_storage:/apk_storage
      - repos_storage:/repos_storage
      - .:/app
    env_file: .env
    networks:
      - pipeline_net
    restart: unless-stopped
volumes:
  apk_storage:
    external: true
  repos_storage:
    external: true
networks:
  pipeline_net:
    external: true
